export const FLIGHTS_LIST_REQUEST = 'FLIGHTS_LIST_REQUEST';
export const FLIGHTS_LIST_SUCCESS = 'FLIGHTS_LIST_SUCCESS';

export const FLIGHT_ADD = 'FLIGHT_ADD';
export const FLIGHT_UPDATE = 'FLIGHT_UPDATE';
export const FLIGHT_DELETE = 'FLIGHT_DELETE';

export const TYPE_SET = 'TYPE_SET';
